version: '3.8'

services:
  flask-api:
    build:
      context: ..
      dockerfile: docker/flask.Dockerfile
    ports:
      - '5050:5000'

  express-api:
    build:
      context: ..
      dockerfile: docker/express.Dockerfile
    ports:
      - '5001:5001'

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - flask-api
      - express-api
