version: '3.8'

services:
  flask-api:
    build:
      context: ..
      dockerfile: docker/flask.Dockerfile
    ports:
      - '5050:5000'
    networks:
      - neuroops-network
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

  express-api:
    build:
      context: ..
      dockerfile: docker/express.Dockerfile
    ports:
      - '5001:5001'
    networks:
      - neuroops-network
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - flask-api
      - express-api
    networks:
      - neuroops-network

networks:
  neuroops-network:
    driver: bridge